name: main

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v1
      - name: Run ShellCheck
        run: shellcheck bin/*

  plugin_test:
    timeout-minutes: 5
    needs: [lint]
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, alpine-latest, centos-latest]
        ver:  [0.9.3]

    runs-on: ${{ matrix.os }}

    steps:
      - name: asdf_plugin_test
        uses: asdf-vm/actions/plugin-test@v3.0.2
        with:
          version: ${{ matrix.ver }}
          command: rustic --version
        env:
          GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
